# Generated by Django 5.1.3 on 2024-12-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jwt_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
