# Generated by Django 5.1.3 on 2024-11-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_appointmentslot_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='host_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='join_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='meeting_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
