# Generated by Django 5.1.3 on 2024-11-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_appointmentrequest_host_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='host_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='join_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
