# Generated by Django 5.1.3 on 2024-11-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_appointmentrequest_host_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='zoom_access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='zoom_refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
