# Generated by Django 5.1.3 on 2024-11-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_doctorprofile_zoom_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='host_url',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='join_url',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='meeting_id',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='zoom_access_token',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='zoom_refresh_token',
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='zoom_meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
