# Generated by Django 5.1.3 on 2024-11-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_appointmentrequest_host_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='zoom_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='zoom_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
