# Generated by Django 5.1.3 on 2024-11-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_doctorprofile_authorization_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentslot',
            old_name='zoom_meeting_link',
            new_name='zoom_meeting_join_url',
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='zoom_meeting_start_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
