# Generated by Django 5.1.3 on 2024-11-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_appointmentslot_zoom_meeting_join_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='zoom_meeting_start_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
