# Generated by Django 5.1.3 on 2024-11-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslot',
            name='zoom_meeting_id',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='zoom_meeting_join_url',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='zoom_meeting_start_url',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='authorization_code',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='zoom_access_token',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='zoom_refresh_token',
        ),
    ]
