# Generated by Django 5.1.3 on 2024-11-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed')], default='scheduled', max_length=50),
        ),
    ]
