# Generated by Django 5.1.3 on 2024-11-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='meeting_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
