# Generated by Django 5.1.3 on 2024-11-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_appointmentslot_meeting_id_delete_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
