# Generated by Django 5.1.3 on 2024-12-03 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_prescription_prescription_text'),
        ('patients', '0020_alter_appointmentrequest_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='patients.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patients.patientinfo'),
        ),
    ]
