# Generated by Django 5.1.3 on 2024-12-03 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_prescription_doctor_alter_prescription_patient'),
        ('patients', '0020_alter_appointmentrequest_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='patients.doctorprofile'),
        ),
    ]
